openapi: 3.0.0
info:
  description: API Specification for Reporting API
  version: 0.1.0
  title: Simulator Reporting API
tags:
  - name: reports
    description: Hub and DFSP Daily Transaction Reports API
paths:
  /reports:
    get:
      tags:
        - reports
      summary: Daily Transaction Reports for the Hub
      description: Daily Transaction Reports for the Hub
      parameters:
        - name: START_DATE_TIME
          in: query
          description: DataTime from which the transactions are needed
          required: true
          schema:
            type: string
        - name: END_DATE_TIME
          in: query
          description: DataTime to which the transactions are needed
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DailyTransactionReport"
        "204":
          description: No Content
        "500":
          description: Bad Request
        "404":
          description: Report is not found on the server
components:
  schemas:
    DailyTransactionReport:
      type: object
      required:
        - senderFsp
      properties:
        senderFsp:
          type: string
        receiverFsp:
          type: string
        transactionId:
          type: string
        transactionType:
          type: string
        createdDate:
          type: string
        senderCurrency:
          type: string
        receiverCurrency:
          type: string
        senderId:
          type: string
        receiverId:
          type: string
        reconciliationAmount:
          type: string
        status:
          type: string
        errorCode:
          type: string
