openapi: 3.0.0
info:
  version: '0.1'
  title: Mojaloop Golden DFSP simulator Test API
  description: Control the simulator
  license:
    name: UNLICENSED
paths:
  /scenarios:
    post:
      description: Send test scenarios
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Scenario'
      responses:
        '200':
          description: The test was successful
        '500':
          description: An error occured processing the request
        "404":
          description: Test file is has errors
  /repository/parties:
    post:
      description: Create a party
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Party'
      responses:
        '204':
          description: The party was created
        '500':
          description: An error occured processing the request
    get:
      description: Get an existing party
      responses:
        '200':
          description: Party data is returned
  /control/initiate-transfer:
    put:
      description: Initiate a quote from a counter-party
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Quote request initiated
components:
  schemas:
    Scenario:
      title: Scenario
      type: object
      description: A party
      properties:
        name:
          type: string
        operation:
          type: string
        body:
          type: object
        from:
          type: object
        to:
          type: object
        amountType:
          type: string
          enum:
          - SEND
          - RECEIVE
        currency:
          type: string
          minLength: 3
          maxLength: 3
        amount:
          pattern: ^([0]|([1-9][0-9]{0,17}))([.][0-9]{0,3}[1-9])?$
          type: string
        transactionType:
          type: string
          enum:
          - TRANSFER
        params:
          type: object
    Party:
      title: Party
      type: object
      description: A party
      properties:
        displayName:
          type: string
        firstName:
          type: string
        middleName:
          type: string
        lastName:
          type: string
        dateOfBirth:
          type: string
        idType:
          type: string
          enum:
          - MSISDN
          - ACCOUNT_NO
        idValue:
          type: string
          minLength: 1
          maxLength: 128
    CurrencyAmount:
      title: CurrencyAmount
      type: object
      description: >-
        A currency amount, consisting of a numeric amount and an ISO4217
        currency code
      properties:
        amount:
          $ref: '#/components/schemas/Amount'
        currency:
          $ref: '#/components/schemas/Currency'
    Amount:
      title: Amount
      type: string
      pattern: '^([0]|([1-9][0-9]{0,17}))([.][0-9]{0,3}[1-9])?$'
      description: >-
        The API data type Amount is a JSON String in a canonical format that is
        restricted by a regular expression for interoperability reasons. This
        pattern does not allow any trailing zeroes at all, but allows an amount
        without a minor currency unit. It also only allows four digits in the
        minor currency unit; a negative value is not allowed. Using more than 18
        digits in the major currency unit is not allowed.
    Currency:
      title: Currency
      description: >-
        The currency codes defined in ISO 4217 as three-letter alphabetic codes
        are used as the standard naming representation for currencies.
      type: string
      minLength: 3
      maxLength: 3
      enum:
        - AED
        - AFN
        - ALL
        - AMD
        - ANG
        - AOA
        - ARS
        - AUD
        - AWG
        - AZN
        - BAM
        - BBD
        - BDT
        - BGN
        - BHD
        - BIF
        - BMD
        - BND
        - BOB
        - BRL
        - BSD
        - BTN
        - BWP
        - BYN
        - BZD
        - CAD
        - CDF
        - CHF
        - CLP
        - CNY
        - COP
        - CRC
        - CUC
        - CUP
        - CVE
        - CZK
        - DJF
        - DKK
        - DOP
        - DZD
        - EGP
        - ERN
        - ETB
        - EUR
        - FJD
        - FKP
        - GBP
        - GEL
        - GGP
        - GHS
        - GIP
        - GMD
        - GNF
        - GTQ
        - GYD
        - HKD
        - HNL
        - HRK
        - HTG
        - HUF
        - IDR
        - ILS
        - IMP
        - INR
        - IQD
        - IRR
        - ISK
        - JEP
        - JMD
        - JOD
        - JPY
        - KES
        - KGS
        - KHR
        - KMF
        - KPW
        - KRW
        - KWD
        - KYD
        - KZT
        - LAK
        - LBP
        - LKR
        - LRD
        - LSL
        - LYD
        - MAD
        - MDL
        - MGA
        - MKD
        - MMK
        - MNT
        - MOP
        - MRO
        - MUR
        - MVR
        - MWK
        - MXN
        - MYR
        - MZN
        - NAD
        - NGN
        - NIO
        - NOK
        - NPR
        - NZD
        - OMR
        - PAB
        - PEN
        - PGK
        - PHP
        - PKR
        - PLN
        - PYG
        - QAR
        - RON
        - RSD
        - RUB
        - RWF
        - SAR
        - SBD
        - SCR
        - SDG
        - SEK
        - SGD
        - SHP
        - SLL
        - SOS
        - SPL
        - SRD
        - STD
        - SVC
        - SYP
        - SZL
        - THB
        - TJS
        - TMT
        - TND
        - TOP
        - TRY
        - TTD
        - TVD
        - TWD
        - TZS
        - UAH
        - UGX
        - USD
        - UYU
        - UZS
        - VEF
        - VND
        - VUV
        - WST
        - XAF
        - XCD
        - XDR
        - XOF
        - XPF
        - YER
        - ZAR
        - ZMW
        - ZWD
  responses: {}
